# Generated by Django 5.2.7 on 2025-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_billdue_note_billdue_type_calendarcell_net_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdue',
            name='type',
            field=models.CharField(choices=[('Bill', 'Bill'), ('Credit Card', 'Credit Card')], max_length=20),
        ),
    ]
